server:
  port: 9012

spring:
  application:
    name: service-consumer9012
  cloud:
#    alibaba:
#      seata:
#        tx-service-group: my_test_tx_group

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
        #指定注册服务的ip
        ip: 192.168.4.206
        #命名空间，这里指向dev
        namespace: cdb2d77b-59b5-4695-960b-567a4adf7b10

    sentinel:
      transport:
        #客户端与控制台通信端口，如占用，自增端口号
        port: 8719
        #dashboard控制台地址
        dashboard: 192.168.4.206:8080
        #指定dashboard客户端ip，不设置很容易指向虚拟ip
        clientIp: 192.168.4.206

      datasource:
        ds1:
          nacos:
            # nacos连接地址
            server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
            # nacos连接的分组
            group-id: SENTINEL_GROUP
            # 路由存储规则
            rule-type: flow
            # 读取配置文件的 data-id
            data-id: service-consumer9012-flow-rules
            # 读取文件类型为json
            data-type: json
            namespace: cdb2d77b-59b5-4695-960b-567a4adf7b10


        # 热点限流
        param-flow:
          nacos:
            # nacos连接地址
            server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
            # nacos连接的分组
            group-id: SENTINEL_GROUP
            # 路由存储规则
            rule-type: param-flow
            # 读取配置文件的 data-id
            data-id: ${spring.application.name}-param-flow-rules
            # 读取文件类型为json
            data-type: json
            namespace: cdb2d77b-59b5-4695-960b-567a4adf7b10


        # 降级规则
        degrade:
          nacos:
            # nacos连接地址
            server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
            # nacos连接的分组
            group-id: SENTINEL_GROUP
            # 路由存储规则
            rule-type: degrade
            # 读取配置文件的 data-id
            data-id: ${spring.application.name}-degrade-rules
            # 读取文件类型为json
            data-type: json
            namespace: cdb2d77b-59b5-4695-960b-567a4adf7b10

management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  level:
    io:
      seata: info


seata:
  #是否开启spring-boot自动装配  默认为true



  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  #是否开启数据源自动代理
  enable-auto-data-source-proxy: true
  #是否使用JDK代理作为数据源自动代理的实现方式
  use-jdk-proxy: false
  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
  client:
    rm:
      async-commit-buffer-limit: 1000
      report-retry-count: 5
      table-meta-check-enable: false
      report-success-enable: false
      saga-branch-register-enable: false
      lock:
        retry-interval: 10
        retry-times: 30
        retry-policy-branch-rollback-on-conflict: true
    tm:
      commit-retry-count: 5
      rollback-retry-count: 5
    undo:
      data-validation: true
      log-serialization: jackson
      log-table: undo_log
    #日志异常输出概率 默认100，目前用于undo回滚失败时异常堆栈输出，百分之一的概率输出，回滚失败基本是脏数据，无需输出堆栈占用硬盘空间
    log:
      exceptionRate: 100
  service:
    vgroup-mapping:
      #
      my_test_tx_group: default
    grouplist:
      default: 127.0.0.1:8091
    enable-degrade: false
    disable-global-transaction: false
  transport:
    shutdown:
      wait: 3
    thread-factory:
      boss-thread-prefix: NettyBoss
      worker-thread-prefix: NettyServerNIOWorker
      server-executor-thread-prefix: NettyServerBizHandler
      share-boss-worker: false
      client-selector-thread-prefix: NettyClientSelector
      client-selector-thread-size: 1
      client-worker-thread-prefix: NettyClientWorkerThread
      worker-thread-size: default
      boss-thread-size: 1
    type: TCP
    server: NIO
    heartbeat: true
    serialization: seata
    compressor: none
    #客户端事务消息请求是否批量合并发送 默认true，false单条发送
    enable-client-batch-send-request: true
  config:
    type: nacos
    consul:
      server-addr: 127.0.0.1:8500
    apollo:
      apollo-meta: http://192.168.1.204:8801
      app-id: seata-server
      namespace: application
    etcd3:
      server-addr: http://localhost:2379
    nacos:
      namespace: 145a6c37-b771-429b-828b-fd0f94ccbd30
      serverAddr: localhost:8848,localhost:8849,localhost:8850
      group: SEATA_GROUP
      userName: "nacos"
      password: "nacos"
    zk:
      server-addr: 127.0.0.1:2181
      session-timeout: 6000
      connect-timeout: 2000
      username: ""
      password: ""
  registry:
    type: nacos
    consul:
      server-addr: 127.0.0.1:8500
    etcd3:
      serverAddr: http://localhost:2379
    eureka:
      weight: 1
      service-url: http://localhost:8761/eureka
    nacos:
      application: seata-server
      server-addr: localhost:8848,localhost:8849,localhost:8850
      namespace: cdb2d77b-59b5-4695-960b-567a4adf7b10
      userName: "nacos"
      password: "nacos"
    redis:
      server-addr: localhost:6379
      db: 0
      password:
      timeout: 0
    sofa:
      server-addr: 127.0.0.1:9603
      region: DEFAULT_ZONE
      datacenter: DefaultDataCenter
      group: SEATA_GROUP
      addressWaitTime: 3000
      application: default
    zk:
      server-addr: 127.0.0.1:2181
      session-timeout: 6000
      connect-timeout: 2000
      username: ""
      password: ""

