server:
  port: 8011

spring:
  application:
    name: service-provider8011
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
        ip: 192.168.2.106
        namespace: cdb2d77b-59b5-4695-960b-567a4adf7b10



    sentinel:
      transport:
        #客户端与控制台通信端口，如占用，自增端口号
        port: 8719
        #dashboard控制台地址
        dashboard: 192.168.4.206:8080
        #指定dashboard客户端ip，不设置很容易指向虚拟ip
        clientIp: 192.168.4.206

      datasource:
        ds1:
          nacos:
            # nacos连接地址
            server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
            # nacos连接的分组
            group-id: SENTINEL_GROUP
            # 路由存储规则
            rule-type: flow
            # 读取配置文件的 data-id
            data-id: service-provider8011-flow-rules
            # 读取文件类型为json
            data-type: json
            namespace: cdb2d77b-59b5-4695-960b-567a4adf7b10