server:
  port: 8011

spring:
  application:
    name: service-provider8011
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 192.168.4.206
        namespace: cdb2d77b-59b5-4695-960b-567a4adf7b10