server:
  port: 8000

spring:
  application:
    name: service-gateway8000
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
        ip: 192.168.4.206
        namespace: cdb2d77b-59b5-4695-960b-567a4adf7b10
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
#            #匹配后提供服务的路由地址
#            #uri: http://localhost:8011
#          uri: lb://service-provider8011
#          predicates:
#            - Path=/testString # 断言，路径相匹配的进行路由

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://docs.spring.io"
            allowedMethods:
            - GET