spring:
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        namespace: 7302d4c3-e843-4db1-af23-777499a2b76a
        group: DEFAULT_GROUP
        ip: 192.168.1.7
        refresh-enabled: true
        enabled: true
        #多配置

      #        ext-config[0]:
      #          data-id: service-nacos-config7000-dev.yaml
      #          group: 测试组
      #          refresh: true


      #
      discovery:
        server-addr: 127.0.0.1:8848
        #指定注册服务的ip
        ip: 192.168.1.7
        namespace: 7302d4c3-e843-4db1-af23-777499a2b76a
  #
  #
  #
  application:
    name: serviceNacosConfig7000
#
server:
  servlet:
    context-path: /nacos


  port: 7000


app:
  time: 2