server:
  port: 8013

spring:
  application:
    name: service-provider-order8013
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848,127.0.0.1:8849,127.0.0.1:8850
        ip: 192.168.4.206
        namespace: cdb2d77b-59b5-4695-960b-567a4adf7b10


    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.199.68.66:3306/seata_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

logging:
  level:
    io:
      seata: debug

    com.yang.study.dao: trace


mybatis:
  mapperLocations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

feign:
  client:
    config:
      default:
        #建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        ConnectTimeOut: 5000
        #指建立连接后从服务端读取到可用资源所用的时间
        ReadTimeOut: 5000